CREATE TABLE SHOPLIST.ITEM_INFO_XML (
  ITEM_ID NUMBER(8,0), 
	PRICE VARCHAR2(40 BYTE), 
	SHOP_ID NUMBER(8,0), 
	BRAND_ID NUMBER(8,0), 
	LOCATION VARCHAR2(3 BYTE), 
	QUANTITY VARCHAR2(40 BYTE), 
	USER_ID NUMBER(8,0), 
	CONSTRAINT PK_ITEM_INFO_XML PRIMARY KEY (ITEM_ID, SHOP_ID, LOCATION, USER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ENABLE, 
	CONSTRAINT FK_ITEM_INFO_USER_ID FOREIGN KEY (USER_ID)
	  REFERENCES SHOPLIST.USERS_XML (USER_ID) ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;

COMMENT ON TABLE SHOPLIST.ITEM_INFO_XML IS 'xml_tag:info';
