CREATE TABLE SMARTLIST.ITEMS_XML (
  ITEM_ID NUMBER(8,0), 
	ITEM_NAME VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	BARCODE VARCHAR2(14 BYTE), 
	USER_ID NUMBER(8,0), 
	CAT_ID NUMBER(8,0), 
	QUANTITY_UNIT VARCHAR2(20 BYTE), 
	CONSTRAINT PK_ITEMS_XML PRIMARY KEY (ITEM_ID, USER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM  ENABLE, 
	CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID)
	  REFERENCES SMARTLIST.USERS_XML (USER_ID) ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM;

COMMENT ON TABLE SMARTLIST.ITEMS_XML IS 'xml_tag:item';
