CREATE TABLE SHOPLIST.USERS_XML (
  USER_ID NUMBER(8,0), 
	USER_NAME VARCHAR2(30 BYTE), 
	BACKUP_FILE VARCHAR2(50 BYTE), 
	BACKUP_DATE DATE, 
	PREVIOUS_BACKUP_FILE VARCHAR2(50 BYTE), 
	BACKUP_RESULT VARCHAR2(7 BYTE), 
	PREVIOUS_BACKUP_DATE DATE, 
	PREVIOUS_USER_NAME VARCHAR2(30 BYTE), 
	USER_NAME_CHANGE_DATE DATE, 
	PRIMARY KEY (USER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ENABLE, 
	CONSTRAINT CHK_BACKUP_RESULT CHECK (backup_result in ('SUCCESS','FAIL','N/A')) ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;

COMMENT ON TABLE SHOPLIST.USERS_XML  IS 'xml_tag:user';
